azs:
- name: z1
  cloud_properties:
    zone: us-west1-b
- name: z2
  cloud_properties:
    zone: us-east1-c
- name: z3
  cloud_properties:
    zone: us-east1-b
- name: mysql_z1
  cloud_properties:
    zone: us-east1-b
disk_types:
- name: 50GB
  disk_size: 51200
  cloud_properties:
    encrypted: true
    type: pd-standard
networks:
- name: vip
  type: vip
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [8.8.8.8, 8.8.4.4]
    azs: [z1, z2]
    cloud_properties:
      network_name: bosh-vpc
      subnetwork_name: bosh-subnet
      ephemeral_external_ip: true
      tags: [internal, concourse]
vm_types:
- name: t2.small
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 50
    root_disk_type: pd-standard
- name: m3.medium
  cloud_properties:
    machine_type: n1-standard-8
    root_disk_size_gb: 50
    root_disk_type: pd-standard
vm_extensions:
- name: 5GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 5120
      type: pd-standard
- name: 10GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 10240
      type: pd-standard
- name: 50GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk:
      size: 51200
      type: pd-standard
compilation:
  az: z1
  network: private
  reuse_compilation_vms: true
  vm_type: m3.medium
  workers: 4
  vm_extensions:
  - 50GB_ephemeral_disk
